config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'application#index'
  resources :messages, :only => [:index, :new, :create, :show]
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  validates :name, :phone, :presence => true
end

app/models/message.rb
class Message < ActiveRecord::Base
  before_create :send_sms

private

  def send_sms
    begin
      response = RestClient::Request.new(
        :method => :post,
        :url => 'https://api.twilio.com/2010-04-01/Accounts/AC032a930f87c16f039f03517e32d6b7ff/Messages.json',
        :user => ENV['TWILIO_ACCOUNT_SID'],
        :password => ENV['TWILIO_AUTH_TOKEN'],
        :payload => { :Body => body,
                      :From => from,
                      :To => to }
      ).execute
    rescue RestClient::BadRequest => error
      message = JSON.parse(error.response)['message']
      errors.add(:base, message)
      throw(:abort)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :contacts, dependent: :destroy       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = current_user.contacts.all
  end

  def new
    @contact = current_user.contacts.new
  end

  def create
    @contact = current_user.contacts.new(contact_params)
    if @contact.save
      flash[:notice] = "Your contact was saved"
      redirect_to contacts_path
    else
      render 'new'
    end
  end

  def show
    @contact = Contact.find(params[:id])
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :phone)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end

  def new
    @message = Message.new
  end

  def create
    @messages = Message.all
    @message = Message.new(message_params)
    if @message.save
      flash[:notice] = "your message was sent!"
      respond_to do |format|
        format.html { redirect_to messages_path }
        format.js
      end
    else
      flash[:notice] = 'Message unable to be saved'
      render 'new'
    end
  end

  def show
    @message = Message.find(params[:id])
  end

private

  def message_params
    params.require(:message).permit(:to, :from, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<%= link_to "New Contact", new_contact_path %>
<%= link_to "Contacts", contacts_path %>

app/views/contacts/index.html.erb
<% if @contacts.any? %>
  <ul>
    <% @contacts.each do |contact| %>
      <li><%= link_to contact.name, contact_path(contact) %></li>
    <% end %>
  </ul>
<% end %>

app/views/contacts/new.html.erb
<%= form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :phone %>
  <%= f.phone_field :phone %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Texter1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:notice] %>
    <div class="container">
      <%= yield %>
    </div>  
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for @message, remote: true do |f| %>
  <%= f.label :to %>
  <%= f.collection_select :to, Contact.all, :phone, :name, include_blank: true %>
  <%= f.label :from %>
  <%= f.text_field :from %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit %>
<% end %>

app/views/messages/_index.html.erb
<% @messages.each do |message| %>
  <li><%= link_to message.id, message_path(message)</li>
<% end %>

app/views/messages/create.js.erb
$("form").remove();
$("new_message_link").show();
$("#messages_index").html('<%= j render "index" %>')

app/views/messages/index.html.erb
<h1>Messages</h1>

<%= link_to "New message", new_message_path, id: "new_message_link", remote: true, class: "btn btn-success" %>
<div id="messages_index">
  <%= render "index" %>
</div>

app/views/messages/new.html.erb
<h1>New Message</h1>

<% if @message.errors.any? %>
  <p>Something went wrong:</p>
  <ul>
    <% @message.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= render "form" %>

app/views/messages/new.js.erb
$("#new_message_link").hide().after('<%= j render("form") %>');

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>